# Generated by Django 2.0.9 on 2020-05-30 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('markets', '0001_initial'),
        ('schedule', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_client', related_query_name='users_clients', to='clients.Client'),
        ),
        migrations.AddField(
            model_name='market',
            name='schedule',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_schedule', related_query_name='users_schedules', to='schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='market',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_staff', related_query_name='users_staffs', to='staff.Staff'),
        ),
    ]
