# Generated by Django 2.0.9 on 2020-08-11 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('markets', '0003_auto_20200811_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketpassrequest',
            name='markets',
        ),
        migrations.RemoveField(
            model_name='marketpassrequest',
            name='schedule',
        ),
        migrations.AddField(
            model_name='countermarket',
            name='markets',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='passrequest', to='markets.Market'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countermarket',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_schedule', related_query_name='users_schedules', to='schedule.Schedule'),
        ),
    ]
