# Generated by Django 2.0.9 on 2020-08-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_auto_20200812_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketpassrequest',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='contador para el pdf'),
        ),
    ]
