# Generated by Django 2.0.9 on 2020-08-17 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_marketpassrequest_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countermarket',
            options={'verbose_name': 'Conteo de pases por Mercado', 'verbose_name_plural': 'conteos de pases por Mercados'},
        ),
        migrations.AlterModelOptions(
            name='marketpassrequest',
            options={'verbose_name': 'Registro de  pase por Mercado', 'verbose_name_plural': 'Registros de pases por Mercados'},
        ),
        migrations.AlterField(
            model_name='marketpassrequest',
            name='counter_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_pass_requests', to='markets.CounterMarket'),
        ),
    ]
