# Generated by Django 2.0.9 on 2020-05-30 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryarea',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
